/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as PharmacistsRouteImport } from './routes/pharmacists'
import { Route as PharmacistOrderRouteImport } from './routes/pharmacist-order'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as ConsultationDetailRouteImport } from './routes/consultation-detail'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistsRoute = PharmacistsRouteImport.update({
  id: '/pharmacists',
  path: '/pharmacists',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistOrderRoute = PharmacistOrderRouteImport.update({
  id: '/pharmacist-order',
  path: '/pharmacist-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationDetailRoute = ConsultationDetailRouteImport.update({
  id: '/consultation-detail',
  path: '/consultation-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/articles': typeof ArticlesRoute
  '/consultation-detail': typeof ConsultationDetailRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mobile': typeof MobileRoute
  '/otp': typeof OtpRoute
  '/pharmacist-order': typeof PharmacistOrderRoute
  '/pharmacists': typeof PharmacistsRoute
  '/professionals': typeof ProfessionalsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/articles': typeof ArticlesRoute
  '/consultation-detail': typeof ConsultationDetailRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mobile': typeof MobileRoute
  '/otp': typeof OtpRoute
  '/pharmacist-order': typeof PharmacistOrderRoute
  '/pharmacists': typeof PharmacistsRoute
  '/professionals': typeof ProfessionalsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/articles': typeof ArticlesRoute
  '/consultation-detail': typeof ConsultationDetailRoute
  '/consultations': typeof ConsultationsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/mobile': typeof MobileRoute
  '/otp': typeof OtpRoute
  '/pharmacist-order': typeof PharmacistOrderRoute
  '/pharmacists': typeof PharmacistsRoute
  '/professionals': typeof ProfessionalsRoute
  '/profile': typeof ProfileRoute
  '/role': typeof RoleRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/articles'
    | '/consultation-detail'
    | '/consultations'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/mobile'
    | '/otp'
    | '/pharmacist-order'
    | '/pharmacists'
    | '/professionals'
    | '/profile'
    | '/role'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/articles'
    | '/consultation-detail'
    | '/consultations'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/mobile'
    | '/otp'
    | '/pharmacist-order'
    | '/pharmacists'
    | '/professionals'
    | '/profile'
    | '/role'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/articles'
    | '/consultation-detail'
    | '/consultations'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/mobile'
    | '/otp'
    | '/pharmacist-order'
    | '/pharmacists'
    | '/professionals'
    | '/profile'
    | '/role'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ArticlesRoute: typeof ArticlesRoute
  ConsultationDetailRoute: typeof ConsultationDetailRoute
  ConsultationsRoute: typeof ConsultationsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MobileRoute: typeof MobileRoute
  OtpRoute: typeof OtpRoute
  PharmacistOrderRoute: typeof PharmacistOrderRoute
  PharmacistsRoute: typeof PharmacistsRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ProfileRoute: typeof ProfileRoute
  RoleRoute: typeof RoleRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacists': {
      id: '/pharmacists'
      path: '/pharmacists'
      fullPath: '/pharmacists'
      preLoaderRoute: typeof PharmacistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist-order': {
      id: '/pharmacist-order'
      path: '/pharmacist-order'
      fullPath: '/pharmacist-order'
      preLoaderRoute: typeof PharmacistOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation-detail': {
      id: '/consultation-detail'
      path: '/consultation-detail'
      fullPath: '/consultation-detail'
      preLoaderRoute: typeof ConsultationDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ArticlesRoute: ArticlesRoute,
  ConsultationDetailRoute: ConsultationDetailRoute,
  ConsultationsRoute: ConsultationsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MobileRoute: MobileRoute,
  OtpRoute: OtpRoute,
  PharmacistOrderRoute: PharmacistOrderRoute,
  PharmacistsRoute: PharmacistsRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ProfileRoute: ProfileRoute,
  RoleRoute: RoleRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
